find_speaker_clashes: avoid crash without a talk or a page
If a user creates a schedule item and adds them to the schedule before
associating a talk or a page, this causes a crash, because `speakers`
will not be defined.

    UnboundLocalError: cannot access local variable 'speakers' where it
    is not associated with a value